### ISSUE TITLE
Рефакторинг: проверка на существование элемента или атрибута

### ISSUE THREAD

**Issue by polRk** [puux/trade-changer#1]
На примере файла sensor.js.

`
var seconds = Math.floor(parseInt(element.getAttribute("data")) - Math.round(new Date().getTime()/1000));
`
1. Следует использовать const
2. element.getAttribute("data") может быть **null** и тогда число будет **NaN**
3. Следует увеличить секунды до миллисекунд, а не делить миллисекунды на 1000 и округлять (разница может быть в 1 секунду)

`
    var nodes = $("table")[isNewStyle ? 1 : 2].childNodes[0];
`
1. Селектор выберет все table на странице.
2. Нет проверки на наличие $("table")
3. Нет проверки на наличие $("table")[1] или $("table")[1] - может быть undefined
4. Нет проверки на наличие дочерних элементов, childNodes[0] - может быть undefined

`
      var planet = nodes.childNodes[i].childNodes[3] ? nodes.childNodes[i].childNodes[3].innerHTML : "";
`
1. Нет проверки на undefined. 
childNodes[3] - может быть undefined и childNodes[3].innerHTML - вызовет ошибку

`
$(rows).insertAfter(row);
`
1. Запись читается справа налево, а код должен читаться слева направо

**Comment by polRk** [comment]
В общем стоит переписать скрипт

**Comment by puux** [comment]
> Следует использовать const

Все дополнения пишутся с охватом максимального количества устройст без использования фишек современного стандарта JS. const, let, стрелочные функции, классы и прочее допустимо только для приложений внутреннего использования

> element.getAttribute("data") может быть null и тогда число будет NaN

Не может. Атрибут и класс добавляются тегу одновременно.

> Следует увеличить секунды до миллисекунд, а не делить миллисекунды на 1000 и округлять (разница может быть в 1 секунду)

В этом нет никакого смысла, пока от сервера приходят секунды. Как только будут приходить штампы в миллисекундах и не дельта, а абсолютное время, то тогда можно будет задумать и о использовании миллисекунд в этом месте.

Все проверки существования элементов так же не имеют смысла - если в игре меняются шаблоны, то плагин что с проверкой, что без нее работать перестанет. Проверки и ручной вывод ошибок в консоль об отсутствии чего-то на странице это пустая трата времени в данном случае, которая никому ничего не даст. В некоторых плагинах есть цепочки из большого количества childNodes.childNodes... - вы просто заколебетесь проверять наличие каждого уровня, код вырастет на 30-50%, а и без того низкая читаемость снизится еще на порядок.

**Comment by polRk** [comment]
> Не может. Атрибут и класс добавляются тегу одновременно.

Вам следует писать на typescript. И тип у него string | null

> В некоторых плагинах есть цепочки из большого количества childNodes.childNodes... - вы просто заколебетесь проверять наличие каждого уровня, код вырастет на 30-50%, а и без того низкая читаемость снизится еще на порядок.

Видимо вы плохо представляете, что если структура изменится, весь ваш код сломается, и влечет неработоспособностью основного кода сайта, как это было пару дней назад, когда  ваши плагины сломали всплывающее окно при наведении.

Нет ничего плохого в том, что код увеличится, зато, любой кто использует ваш код, может не боятся ошибок в консоле и неработоспособности основного сайта.

Обрабатывать ошибки - признак качественного кода.

**Comment by puux** [comment]
> Вам следует писать на typescript. И тип у него string | null

Владислав, как вы себе это представляете? 50-60% кода в плагине это разбор DOM и интеграция кусков HTML в нужные места страницы. Что даст для этих операций использование TS? Правильно - ничего. А прописывать d.ts шаблоны для 2х с половиной функций из внешних зависимостей займет времени больше, чем вся последующая поддержка плагина не говоря уже про развертывание окружения для сборки TS всякий раз, когда нужно будет поправить одну букву в скрипте.

> Видимо вы плохо представляете, что если структура изменится, весь ваш код сломается, и влечет неработоспособностью основного кода сайта

Скорей всего это вы не очень понимаете, что происходит в этом случае. Т.к. плагины загружаются на сайт последними, то любые ошибки в них (завязанные на DOM) на работе основного сайта не отразятся ровным счетом никак.

>  как это было пару дней назад, когда ваши плагины сломали всплывающее окно при наведении.

Это случилось не из-за ошибок в плагинах, а из-за того, что авторы скриптов, которые ипользуются в игре, добавили в window глобальные переменные с именами в одну букву, которые как вам вероятно известно, очень часто используются в счетчиках, циклах и временных переменных. 

> Нет ничего плохого в том, что код увеличится, зато, любой кто использует ваш код, может не боятся ошибок в консоле и неработоспособности основного сайта.

Вы просто не совсем правильно понимаете, что есть плагин. Эти скрипты хоть и называются "плагинами" по факту это просто патчи на клиентской стороне, потому что они не используют никакого API, а просто патчат нужные участки "кода" со всеми от сюда вытекающими - изменили пару строк в исходном шаблоне и все, патч работать перестал. Их главная задача - показать игрокам и разработчику, как можно сделать лучше, чтобы он интегрировал этот патч в исходные шаблоны игры и не более того. 

> Обрабатывать ошибки - признак качественного кода.

Признак качественно кода это в первую очередь хорошая архитектура. А когда её нет от слова совсем, то тут уже ничего не спасет. Вы просто потратите кучу времени на то, что не будет нужно никому и даже вам.
